### PR TITLE
composer: add PHP and symfony\yaml dependencies

### PR DESCRIPTION
**Pull request by TomasVotruba**
I found your repo on http://stackoverflow.com/questions/29589937/travis-ci-build-fails-for-php-5-4-while-trying-to-run-composer

I'd like to help you, so I suggest few improvements.

Also, stable libraries (>=1.0) usually don't require and asterix version (4.5.*). That being said, requiring version "~4.5" for PHPUnit makes more sense.

### CODE REVIEW

**Comment by CodeRichard** [comment]
Thank you very much for your suggestions. I'm still not 100% known with Composer and when to use what symbol.

**Comment by TomasVotruba** [comment]
You're welcome.

>  I'm still not 100% known with Composer and when to use what symbol.

Neither am I. The easiest is to check projects you already use. E.g. I use Symfony so I get inspired by it's `composer.json`.

**Comment by CodeRichard** [comment]
Like how I used [this repo](https://github.com/alexgarett/violin) for the travis.yml. (It's very awesome)

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
